import type { NextPage } from 'next'
import Head from 'next/head'
import ProductContainer from '../components/ProductContainer'

const Home: NextPage = () => {

  return (
    <div>
      <Head>
        <title>E-commerce Homepage</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/favicon-32x32.png" />
      </Head>
      <main>
        <ProductContainer/>
      </main>
    </div>
  )
}

export default Home
